logging:
  level:
    root: warn
    org.springframework: warn
    space.nixus: debug
services:
  pubtrans:
    auth: https://auth-dot-micro-services-378415.appspot.com
    main: https://micro-services-378415.appspot.com
spring:
  main:
    banner-mode: off
  security:
    filter:
      order: 10
  cloud:
    gcp:
      credentials:
        location: file:///C:/Users/noocn/keys/micro-services-378415-83c3c6430e0a.json
      datastore:
        namespace: micro-services
      project-id: micro-services-378415
space:
  nixus:
    auth:
      challenge-minutes: 2
      issuer: space.nixus.micro-services-378415
      expiry-minutes: 120
