logging:
  level:
    root: warn
    org.springframework: warn
    space.nixus: debug
spring:
  main:
    banner-mode: off
  cloud:
    gcp:
      datastore:
        namespace: micro-services
      credentials:
        location: file:///C:/Users/noocn/keys/micro-services-378415-83c3c6430e0a.json
      project-id: micro-services-378415
  security:
    filter:
      order: 10
