spring:
  profiles:
    active:
      - dev
      - endpoints
  security:
    filter:
      order: 10
  cloud:
    gcp:
      credentials:
        location: classpath:micro-services-378415-83c3c6430e0a.json
      datastore:
        namespace: micro-services
      project-id: micro-services-378415
space:
  nixus:
    pubtrans:
      challenge-minutes: 2
      issuer: space.nixus.micro-services-378415
      expiry-minutes: 120
