spring:
  profiles:
    active:
      - dev
      - endpoints
  security:
    filter:
      order: 10
  cloud:
    gcp:
      datastore:
        namespace: micro-services
      project-id: micro-services-378415
space:
  nixus:
    pubtrans:
      challenge-minutes: 2
      issuer: space.nixus.micro-services-378415
      expiry-minutes: 120
      unique: 7beb1f70-b96f-4b41-841a-acf5e2da6586
